# Generated by Django 5.1.2 on 2024-10-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('savings', 'Savings Account'), ('current', 'Current Account')], max_length=7)),
                ('initial_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('password', models.CharField(default='*********', max_length=128)),
                ('terms_agreed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'AccountUsers',
            },
        ),
    ]
