# Generated by Django 5.1.2 on 2024-10-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0002_bankaccountuser_rename_accountusers_accountuser_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountUser',
        ),
    ]
