# Generated by Django 5.1.2 on 2024-10-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0003_delete_accountuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccountuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
