# Generated by Django 5.1.2 on 2024-10-18 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atm', '0005_alter_bankaccountuser_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccountuser',
            old_name='initial_deposit',
            new_name='deposit',
        ),
    ]
